spring:
  liquibase:
    change-log: classpath:/migration/master-changelog.xml
  datasource:
    url: jdbc:postgresql://localhost:5432/user-profile
    username: postgres
    password: linh2002
  application:
    name: user-profile-service
