spring:
  liquibase:
    change-log: classpath:/migration/master-changelog.xml
  datasource:
    url: jdbc:postgresql://localhost:5432/user-profile
    username: postgres
    password: linh2002
  application:
    name: user-profile-service

  mail:
    default-encoding: UTF-8
    host: smtp.gmail.com
    username:
    password:
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    protocol: smtp
    test-connection: false
    template:
      name: mail-template.html

application:
  authentication:
    access_token:
      jwt_secret: FHghAas4HaafJA5ghk3HAF
      life_time: 3600000
    refresh_token:
      jwt_secret: ZFDF8GJS4ADFA64ASDeimY
      life_time: 3000000

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs

  swagger-ui:
    enabled: true
    path: /swagger-ui.html

server:
  port: 8080